"""add extracted_text to materials

Revision ID: 01394e563631
Revises: 8a8a027bf1c8
Create Date: 2026-08-10 15:00:46.523879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01394e563631'
down_revision: Union[str, Sequence[str], None] = '8a8a027bf1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'extracted_text')
    # ### end Alembic commands ###
