"""create learning_resource_selections

Revision ID: a476d8821a90
Revises: 01394e563631
Create Date: 2026-08-13 15:21:27.584416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a476d8821a90'
down_revision: Union[str, Sequence[str], None] = '01394e563631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_resource_selections',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('beginner','intermediate','advanced') OR difficulty IS NULL", name='ck_learning_resources_difficulty'),
    sa.CheckConstraint("resource_type IN ('official_docs','tutorial','article','video','practice','reference','course','other')", name='ck_learning_resources_resource_type'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', name='uq_learning_resources_user_url')
    )
    op.create_index(op.f('ix_learning_resource_selections_subject_id'), 'learning_resource_selections', ['subject_id'], unique=False)
    op.create_index('ix_learning_resources_user_created', 'learning_resource_selections', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_learning_resources_user_created', table_name='learning_resource_selections')
    op.drop_index(op.f('ix_learning_resource_selections_subject_id'), table_name='learning_resource_selections')
    op.drop_table('learning_resource_selections')
    # ### end Alembic commands ###
