import { CalendarDays, CheckCircle2, Flag, Sparkles, Target } from 'lucide-react'
import { StudyPlanPreview } from '../components/dashboard/StudyPlanPreview'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { PageHeader } from '../components/ui/PageHeader'
import { ProgressBar } from '../components/ui/ProgressBar'
import { exam, studyGoals, todaysStudyPlan, upcomingTasks } from '../data/mockData'

export function StudyPlanPage() {
  return (
    <>
      <PageHeader
        title="Study Plan"
        subtitle="Your adaptive study planner — generated by AI in a later phase."
      />

      <section className="grid grid-cols-1 gap-4 lg:grid-cols-3">
        {/* Exam countdown */}
        <Card className="border-indigo-200 bg-indigo-50/60">
          <div className="flex items-center gap-3">
            <span className="rounded-xl bg-indigo-600 p-2.5 text-white">
              <Flag className="h-5 w-5" aria-hidden="true" />
            </span>
            <div>
              <p className="text-sm font-semibold">{exam.title}</p>
              <p className="text-xs text-slate-500">{exam.date}</p>
            </div>
          </div>
          <p className="mt-4 text-3xl font-bold tracking-tight text-indigo-700">
            {exam.daysRemaining} days
          </p>
          <p className="text-sm text-slate-500">remaining</p>
        </Card>

        {/* Study goal */}
        <Card className="lg:col-span-1">
          <div className="flex items-center justify-between">
            <h2 className="text-base font-semibold">Study goals</h2>
            <Target className="h-5 w-5 text-slate-400" aria-hidden="true" />
          </div>
          <div className="mt-4 space-y-5">
            {studyGoals.map((goal) => (
              <div key={goal.id}>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-slate-600">{goal.label}</span>
                  <span className="font-semibold">
                    {goal.current} <span className="font-normal text-slate-400">/ {goal.target}</span>
                  </span>
                </div>
                <ProgressBar value={goal.percent} className="mt-2" />
              </div>
            ))}
          </div>
        </Card>

        {/* Generate plan */}
        <Card className="flex flex-col justify-center text-center lg:col-span-1">
          <span className="mx-auto rounded-2xl bg-indigo-50 p-3 text-indigo-600">
            <Sparkles className="h-6 w-6" aria-hidden="true" />
          </span>
          <h2 className="mt-4 text-base font-semibold">Generate Study Plan</h2>
          <p className="mt-1 text-sm text-slate-500">
            Let ByteBrains build your personalized schedule.
          </p>
          <Button variant="secondary" className="mt-5">
            Generate Study Plan
          </Button>
          <p className="mt-3 text-xs text-slate-400">
            Powered by AI — arrives in the next phase.
          </p>
        </Card>
      </section>

      <section className="mt-10 grid grid-cols-1 gap-4 lg:grid-cols-2">
        <StudyPlanPreview items={todaysStudyPlan} />

        <Card>
          <div className="flex items-center justify-between">
            <h2 className="text-base font-semibold">Today's tasks</h2>
            <Badge tone="indigo">6 of 8 done</Badge>
          </div>
          <ul className="mt-2 divide-y divide-slate-100">
            {todaysStudyPlan.map((task) => (
              <li key={task.id} className="flex items-center gap-3 py-3">
                <CheckCircle2 className="h-5 w-5 shrink-0 text-slate-300" aria-hidden="true" />
                <span className="text-sm font-medium text-slate-800">{task.title}</span>
                <span className="ml-auto text-xs text-slate-400">{task.time}</span>
              </li>
            ))}
            {upcomingTasks.map((task) => (
              <li key={task.id} className="flex items-center gap-3 py-3">
                <CalendarDays className="h-5 w-5 shrink-0 text-slate-300" aria-hidden="true" />
                <span className="text-sm text-slate-500">{task.title}</span>
                <span className="ml-auto text-xs text-slate-400">{task.when}</span>
              </li>
            ))}
          </ul>
        </Card>
      </section>
    </>
  )
}